### ISSUE TITLE
Hi, missed ya!

### ISSUE THREAD

**Issue by Teku16** [Levtastic/HypocrisyBot#2]
Lev! I haven't talked to you in years, your skype stopped being active like 2-3 years ago, and I'm dying to catch up! Hopefully, you remember me, I played Toontown a lot and used kittenbot, then you taught me a lot about programming. This was the only way I could find to contact you on here, so forgive me.... we need to reconnect! 

- Mikey

**Comment by Levtastic** [comment]
Hey man it's good to hear from you! Yeah I haven't used skype in such a long time - most of my online socialising is done with Discord these days - if you use it, you can add me, it would be good to catch up! I'm `Lev#8509` on there.
